# Site settings
title: Look4Service
email: look4service@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new sidte here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: look4service
facebook_username: look4service
github_username:  jekyll

# Build settings
markdown: kramdown
